contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pcgr channel"
    url: https://nfcore.slack.com/channels/pcgr
    about: Discussion about the nf-core/pcgr pipeline
